import {BuildingNames} from "./Building";
import {BuffRange} from "./Buff";

let quests = [
    {
        name:"市民健身",
        buffs:[
            [
                {
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:150
                }, {
                    name:BuildingNames.Residential,
                    buff:80
                }, {
                    name:BuildingNames.Bungalow,
                    buff:80
                }
            ], [
                {
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:120
                }, {
                    name:BuildingNames.GardenHouse,
                    buff:120
                }, {
                    name:BuildingNames.SteelStructureHouse,
                    buff:60
                }
            ], [
                {
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:150
                }, {
                    name:BuildingNames.SteelStructureHouse,
                    buff:80
                }, {
                    name:BuildingNames.Residential,
                    buff:80
                }
            ]
        ]
    }, {
        name:"反腐倡廉",
        buffs:[
            [
                {
                    name:BuffRange.Global,
                    buff:20
                }
            ]
        ]
    }, {
        name:"服务业示范区",
        buffs:[
            [
                {
                    name:BuildingNames.GasStation,
                    buff:150
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:150
                },{
                    name:BuildingNames.HardwareStore,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.BusinessCenter,
                    buff:150
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:100
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.ConvenienceStore,
                    buff:150
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.GasStation,
                    buff:100
                },{
                    name:BuildingNames.ClothingStore,
                    buff:100
                },{
                    name:BuildingNames.HardwareStore,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.BusinessCenter,
                    buff:150
                },{
                    name:BuildingNames.ClothingStore,
                    buff:150
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:100
                }
            ]
        ]
    }, {
        name:"绿色工厂",
        buffs:[
            [
                {
                    name:BuildingNames.FoodFactory,
                    buff:100
                },{
                    name:BuildingNames.PowerPlant,
                    buff:150
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.TextileMill,
                    buff:150
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                },{
                    name:BuildingNames.FoodFactory,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.FoodFactory,
                    buff:150
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                },{
                    name:BuildingNames.PowerPlant,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.SteelPlant,
                    buff:150
                },{
                    name:BuildingNames.FoodFactory,
                    buff:100
                },{
                    name:BuildingNames.WaterPlant,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.SteelPlant,
                    buff:150
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                },{
                    name:BuildingNames.WaterPlant,
                    buff:150
                }
            ]
        ]
    }, {
        name:"和谐家园",
        buffs:[
            [
                {
                    name:BuffRange.Residence,
                    buff:30
                },{
                    name:BuildingNames.SmallApartment,
                    buff:200
                },{
                    name:BuildingNames.Chalet,
                    buff:50
                }
            ],[
                {
                    name:BuffRange.Residence,
                    buff:30
                },{
                    name:BuildingNames.TalentApartment,
                    buff:100
                },{
                    name:BuildingNames.SmallApartment,
                    buff:150
                }
            ],[
                {
                    name:BuffRange.Residence,
                    buff:30
                },{
                    name:BuildingNames.GardenHouse,
                    buff:150
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ]
        ]
    }, {
        name:"保税商圈",
        buffs:[
            [
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.BusinessCenter,
                    buff:100
                },{
                    name:BuildingNames.ClothingStore,
                    buff:150
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.BusinessCenter,
                    buff:100
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:150
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.BusinessCenter,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.BusinessCenter,
                    buff:100
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:150
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.BusinessCenter,
                    buff:100
                },{
                    name:BuildingNames.HardwareStore,
                    buff:150
                }
            ]
        ]
    }, {
        name:"工业综合体",
        buffs:[
            [
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.TencentMachinery,
                    buff:100
                },{
                    name:BuildingNames.FoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.TencentMachinery,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.TencentMachinery,
                    buff:100
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.TencentMachinery,
                    buff:100
                },{
                    name:BuildingNames.WaterPlant,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.TencentMachinery,
                    buff:100
                },{
                    name:BuildingNames.PowerPlant,
                    buff:100
                }
            ],
        ]
    }, {
        name:"文明城市",
        buffs:[
            [
                {
                    name:BuffRange.Global,
                    buff:10
                }
            ],[
                {
                    name:BuffRange.Global,
                    buff:20
                },{
                    name:BuffRange.Residence,
                    buff:30
                }
            ]
        ]
    }, {
        name:"美丽街区",
        buffs:[
            [
                {
                    name:BuildingNames.TalentApartment,
                    buff:200
                },{
                    name:BuildingNames.Residential,
                    buff:100
                },{
                    name:BuildingNames.Chalet,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:200
                },{
                    name:BuildingNames.SteelStructureHouse,
                    buff:100
                },{
                    name:BuildingNames.Chalet,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.GardenHouse,//标红了
                    buff:200
                },{
                    name:BuildingNames.SteelStructureHouse,
                    buff:100
                },{
                    name:BuildingNames.Bungalow,
                    buff:100
                }
            ]
        ]
    }, {
        name:"营商环境",
        buffs:[
            [
                {
                    name:BuffRange.Supply,
                    buff:20
                }
            ],[
                {
                    name:BuffRange.Supply,
                    buff:20
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Supply,
                    buff:20
                },{
                    name:BuildingNames.FoodFactory,
                    buff:100
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Supply,
                    buff:20
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                }
            ]
        ]
    }, {
        name:"招商引资",
        buffs:[
            [
                {
                    name:BuildingNames.TencentMachinery,
                    buff:200
                },{
                    name:BuildingNames.FolkFood,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.TencentMachinery,
                    buff:200
                },{
                    name:BuildingNames.PartsFactory,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.FolkFood,
                    buff:100
                },{
                    name:BuildingNames.SteelPlant,
                    buff:200
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.FolkFood,
                    buff:100
                },{
                    name:BuildingNames.TencentMachinery,
                    buff:200
                }
            ]
        ]
    }, {
        name:"就业创业",
        buffs:[
            [
                {
                    name:BuildingNames.SteelPlant,
                    buff:200
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                },{
                    name:BuildingNames.ClothingStore,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.TextileMill,
                    buff:200
                },{
                    name:BuildingNames.FoodFactory,
                    buff:100
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.ClothingStore,
                    buff:100
                },{
                    name:BuildingNames.FoodFactory,
                    buff:200
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.ClothingStore,
                    buff:200
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                }
            ]
        ]
    }, {
        name:"未来社区",
        buffs:[
            [
                {
                    name:BuildingNames.RevivalMansion,
                    buff:100
                },{
                    name:BuildingNames.TalentApartment,
                    buff:100
                },{
                    name:BuildingNames.Bungalow,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.SkyVilla,
                    buff:100
                },{
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:150
                },{
                    name:BuildingNames.SmallApartment,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.RevivalMansion,
                    buff:100
                },{
                    name:BuildingNames.GardenHouse,
                    buff:200
                },{
                    name:BuildingNames.Residential,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.SkyVilla,
                    buff:100
                },{
                    name:BuildingNames.TalentApartment,
                    buff:100
                },{
                    name:BuildingNames.Chalet,
                    buff:150
                }
            ],[
                {
                    name:BuildingNames.GardenHouse,
                    buff:150
                },{
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:150
                },{
                    name:BuildingNames.SteelStructureHouse,
                    buff:100
                }
            ]
        ]
    }, {
        name:"智慧工业园",
        buffs:[
            [
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.PeoplesOil,
                    buff:100
                },{
                    name:BuildingNames.FoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.PeoplesOil,
                    buff:100
                },{
                    name:BuildingNames.WaterPlant,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.PeoplesOil,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.PeoplesOil,
                    buff:100
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Industrial,
                    buff:30
                },{
                    name:BuildingNames.PeoplesOil,
                    buff:100
                },{
                    name:BuildingNames.PowerPlant,
                    buff:100
                }
            ]
        ]
    }, {
        name:"医疗一体化",
        buffs:[
            [
                {
                    name:BuffRange.Online,
                    buff:20
                }
            ]
        ]
    }, {
        name:"四好农村路",
        buffs:[
            [
                {
                    name:BuildingNames.GasStation,
                    buff:100
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:200
                },{
                    name:BuildingNames.Bungalow,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.GasStation,
                    buff:150
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:100
                },{
                    name:BuildingNames.Residential,
                    buff:150
                }
            ]
        ]
    }, {
        name:"国际商圈",
        buffs:[
            [
                {
                    name:BuildingNames.MediaVoice,
                    buff:100
                },{
                    name:BuildingNames.BusinessCenter,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.MediaVoice,
                    buff:100
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:200
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.MediaVoice,
                    buff:100
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:100
                },{
                    name:BuildingNames.HardwareStore,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.MediaVoice,
                    buff:100
                },{
                    name:BuildingNames.GasStation,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.MediaVoice,
                    buff:100
                },{
                    name:BuildingNames.ClothingStore,
                    buff:200
                },{
                    name:BuildingNames.HardwareStore,
                    buff:100
                }
            ]
        ]
    }, {
        name:"交通安全",
        buffs:[
            [
                {
                    name:BuffRange.Offline,
                    buff:20
                },{
                    name:BuildingNames.GasStation,
                    buff:100
                }
            ]
        ]
    }, {
        name:"工业机器人",
        buffs:[
            [
                {
                    name:BuildingNames.SteelPlant,
                    buff:100
                },{
                    name:BuildingNames.TextileMill,
                    buff:100
                },{
                    name:BuildingNames.WoodFactory,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.TextileMill,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:200
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.SteelPlant,
                    buff:100
                },{
                    name:BuildingNames.TextileMill,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.SteelPlant,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:200
                },{
                    name:BuildingNames.WoodFactory,
                    buff:100
                }
            ]
        ]
    }, {
        name:"特色商业街",
        buffs:[
            [
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.FolkFood,
                    buff:150
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.FolkFood,
                    buff:150
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.FolkFood,
                    buff:150
                },{
                    name:BuildingNames.HardwareStore,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.FolkFood,
                    buff:150
                }
            ],[
                {
                    name:BuffRange.Business,
                    buff:30
                },{
                    name:BuildingNames.FolkFood,
                    buff:150
                },{
                    name:BuildingNames.ClothingStore,
                    buff:100
                }
            ]
        ]
    }, {
        name:"绿色出行",
        buffs:[
            [
                {
                    name:BuffRange.Online,
                    buff:20
                },{
                    name:BuildingNames.PeoplesOil,
                    buff:200
                }
            ]
        ]
    }, {
        name:"普惠养老",
        buffs:[
            [
                {
                    name:BuffRange.Offline,
                    buff:10
                }
            ],[
                {
                    name:BuffRange.Offline,
                    buff:20
                },{
                    name:BuildingNames.GardenHouse,
                    buff:100
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Offline,
                    buff:20
                },{
                    name:BuildingNames.Chalet,
                    buff:100
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Offline,
                    buff:20
                },{
                    name:BuildingNames.ChineseSmallBuilding,
                    buff:100
                },{
                    name:BuildingNames.Residential,
                    buff:100
                }
            ]
        ]
    }, {
        name:"清洁能源",
        buffs:[
            [
                {
                    name:BuildingNames.WaterPlant,
                    buff:100
                },{
                    name:BuildingNames.PowerPlant,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.PowerPlant,
                    buff:100
                },{
                    name:BuildingNames.WaterPlant,
                    buff:200
                }
            ]
        ]
    }, {
        name:"电子商务",
        buffs:[
            [
                {
                    name:BuildingNames.BookCity,
                    buff:100
                },{
                    name:BuildingNames.PaperMill,
                    buff:150
                },{
                    name:BuildingNames.ClothingStore,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.TextileMill,
                    buff:150
                },{
                    name:BuildingNames.ClothingStore,
                    buff:100
                },{
                    name:BuildingNames.ConvenienceStore,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.PartsFactory,//标红了
                    buff:150
                },{
                    name:BuildingNames.HardwareStore,
                    buff:100
                },{
                    name:BuildingNames.VegetableMarket,
                    buff:100
                }
            ]
        ]
    }, {
        name:"市民文化节",
        buffs:[
            [
                {
                    name:BuildingNames.MediaVoice,
                    buff:200
                },{
                    name:BuildingNames.BookCity,
                    buff:100
                }
            ],[
                {
                    name:BuffRange.Online,
                    buff:20
                },{
                    name:BuildingNames.BookCity,//标红了
                    buff:200
                }
            ],[
                {
                    name:BuffRange.Online,
                    buff:20
                },{
                    name:BuildingNames.MediaVoice,
                    buff:200
                }
            ]
        ]
    }, {
        name:"家电下乡",//整体标红
        buffs:[
            [
                {
                    name:BuildingNames.PartsFactory,
                    buff:200
                },{
                    name:BuildingNames.HardwareStore,
                    buff:100
                },{
                    name:BuildingNames.PowerPlant,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.BusinessCenter,
                    buff:100
                },{
                    name:BuildingNames.PartsFactory,
                    buff:200
                },{
                    name:BuildingNames.HardwareStore,
                    buff:100
                }
            ]
        ]
    }, {
        name:"招才引智",
        buffs:[
            [
                {
                    name:BuildingNames.RevivalMansion,
                    buff:200
                },{
                    name:BuildingNames.BookCity,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.RevivalMansion,
                    buff:200
                },{
                    name:BuildingNames.TalentApartment,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.RevivalMansion,
                    buff:200
                },{
                    name:BuildingNames.GardenHouse,
                    buff:100
                }
            ]
        ]
    }, {
        name:"强师工程",//整体标黄
        buffs:[
            [
                {
                    name:BuildingNames.BookCity,
                    buff:150
                },{
                    name:BuildingNames.School,
                    buff:150
                }
            ]
        ]
    }, {
        name:"脱贫攻坚",
        buffs:[
            [
                {
                    name:BuildingNames.SteelStructureHouse,
                    buff:150
                },{
                    name:BuildingNames.Residential,
                    buff:150
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.Chalet,
                    buff:150
                },{
                    name:BuildingNames.Bungalow,
                    buff:150
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.SteelStructureHouse,
                    buff:150
                },{
                    name:BuildingNames.Bungalow,
                    buff:150
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ]
        ]
    }, {
        name:"文化产业",
        buffs:[
            [
                {
                    name:BuffRange.Online,
                    buff:20
                },{
                    name:BuildingNames.TalentApartment,
                    buff:150
                }
            ],[
                {
                    name:BuffRange.Online,
                    buff:20
                },{
                    name:BuildingNames.SkyVilla,
                    buff:200
                }
            ]
        ]
    }, {
        name:"平安校园",
        buffs:[
            [
                {
                    name:BuildingNames.School,
                    buff:100
                },{
                    name:BuildingNames.SteelStructureHouse,
                    buff:200
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ],[
                {
                    name:BuildingNames.School,
                    buff:100
                },{
                    name:BuildingNames.Bungalow,
                    buff:100
                },{
                    name:BuildingNames.SmallApartment,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.School,
                    buff:200
                },{
                    name:BuildingNames.Bungalow,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.School,
                    buff:200
                },{
                    name:BuildingNames.Chalet,
                    buff:200
                }
            ],[
                {
                    name:BuildingNames.School,
                    buff:100
                },{
                    name:BuildingNames.Chalet,
                    buff:200
                },{
                    name:BuildingNames.SmallApartment,
                    buff:100
                }
            ]
        ]
    }
];

export default quests;